# SMTP credentials for sending email notifications
SmtpUser     = ""  # Will be set as an encrypted string by the Configuration menu.
SmtpPassword = ""  # Will be set as an encrypted string by the Configuration menu.
EncryptionKey = "p04lCUCXBjDIlpiN1dIjRauOghtmL8f1"  # 32 bytes https://acte.ltd/utils/randomkeygen
SmtpServer   = "smtp.gmail.com"
SmtpPort     = "587"
FromEmail    = "sender@example.org"

# The comma-delimited list of email recipients to receive the updates.
Recipients = ["JohnDoe@example.com", "JaneDoe@example.com"]

# The name of the person that will use the program and send the updates.
Name = "Bill"

# The labels on the buttons. Can be changed to support alternate languages or different purposes.
# Try to keep the length short because of the button size.
Button1Label = "I'm OK"
Button2Label = "Call Me"