// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AmOk():Promise<string>;

export function CallMe():Promise<string>;

export function Init():Promise<void>;
