// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {menu} from '../models';

export function Button1Action():Promise<string>;

export function Button2Action():Promise<string>;

export function Init():Promise<void>;

export function Menu():Promise<menu.Menu>;

export function SaveAction(arg1:string,arg2:string):Promise<string>;
