// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AmOk() {
  return window['go']['main']['App']['AmOk']();
}

export function CallMe() {
  return window['go']['main']['App']['CallMe']();
}

export function Init() {
  return window['go']['main']['App']['Init']();
}
