// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Button1Action() {
  return window['go']['main']['App']['Button1Action']();
}

export function Button2Action() {
  return window['go']['main']['App']['Button2Action']();
}

export function Init() {
  return window['go']['main']['App']['Init']();
}
